# Generated by Django 3.1.5 on 2021-03-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('symbol', models.CharField(max_length=2)),
                ('result', models.CharField(max_length=100000)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
